apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sit7227.azurecr.io/book_catalog:v1
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "4000"
        - name: DATABASE_URL
          value: "postgresql://sit722part3_jhs3_user:sIs5u4ueZ6RxmhTfXrlx5wfs4D9d9lz7@dpg-crlbr2aj1k6c73fq1g50-a.oregon-postgres.render.com/sit722part3_jhs3"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: book-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: sit7227.azurecr.io/inventory_management:v1
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          value: "postgresql://sit722part3_jhs3_user:sIs5u4ueZ6RxmhTfXrlx5wfs4D9d9lz7@dpg-crlbr2aj1k6c73fq1g50-a.oregon-postgres.render.com/sit722part3_jhs3"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: inventory-management